# Generated by Django 2.0.6 on 2018-12-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0002_usersetupmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersetupmodel',
            old_name='user_name',
            new_name='first_name',
        ),
    ]
