# Generated by Django 2.0.6 on 2018-12-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0003_auto_20181210_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('hit_points', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('magic', models.IntegerField(default=0)),
                ('skill', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('faith', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='playercharactermodel',
            name='current_health',
        ),
        migrations.RemoveField(
            model_name='playercharactermodel',
            name='current_strength',
        ),
        migrations.AddField(
            model_name='characterclassesmodel',
            name='classFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoryApp.PlayerCharacterModel'),
        ),
    ]
