# Generated by Django 2.0.6 on 2018-12-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0004_auto_20181210_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclassesmodel',
            name='classFK',
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='classFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StoryApp.CharacterClassesModel'),
        ),
    ]
