# Generated by Django 2.0.6 on 2018-12-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0006_characterclassesmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharactermodel',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='password',
            field=models.CharField(max_length=257, null=True),
        ),
    ]
