# Generated by Django 2.0.6 on 2018-12-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0008_characterclassesmodel_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharactermodel',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='faith',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='movement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharactermodel',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
