# Generated by Django 2.0.6 on 2018-12-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryApp', '0009_auto_20181219_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharactermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='playercharactermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='playercharactermodel',
            name='password',
        ),
    ]
